# .github/workflows/sprint_b.yml
name: Sprint B – Hyper-Perf 100 %

on:
  workflow_dispatch:      # <- déclenchement par bouton "Run workflow"

jobs:
  sprint-b:
    runs-on: ubuntu-latest
    env:
      META_AUTORUN_SPRINT_B: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run Sprint B pipeline
        run: python ci/pack_and_version.py --sprint B
      - name: Upload ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: zips
          path: versions/*.zip
