name: Sprint B – Hyper-Perf 100 %

on:
  workflow_dispatch:          # déclenché par bouton “Run workflow”

jobs:
  sprint-b:
    runs-on: ubuntu-latest
    env:
      META_AUTORUN_SPRINT_B: "1"
    steps:
      - uses: actions/checkout@v4

      # (optionnel) télécharge le ZIP r55 depuis la Release
      # - name: Download r55 asset
      #   run: |
      #     URL=$(curl -s \
      #       https://api.github.com/repos/<owner>/<repo>/releases/latest |
      #       jq -r '.assets[]|select(.name|endswith("r55.zip"))|.browser_download_url')
      #     mkdir -p versions
      #     curl -L -o versions/r55.zip "$URL"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Sprint B pipeline
        run: python ci/pack_and_version.py --sprint B

      - name: Upload ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: zips
          path: versions/*.zip
