name: Sprint B – Hyper-Perf 100 %

on:
  repository_dispatch:           # GitHub API déclenche
    types: [run-sprint-b]

jobs:
  sprint-b:
    runs-on: ubuntu-latest
    env:
      META_AUTORUN_SPRINT_B: "1"   # dit au script de lancer Sprint B
    steps:
      - uses: actions/checkout@v4      # récupère le code
      - uses: actions/setup-python@v5  # installe Python 3.10
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run Sprint B pipeline
        run: python ci/pack_and_version.py --sprint B
      - name: Upload ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: zips
          path: versions/*.zip
